name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: ./print_ip/Doxyfile
          working-directory: .
      
      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./print_ip/doc/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages